### ISSUE TITLE
Failed to activate the atom-date-helpers package

### ISSUE THREAD

**Issue by Zlitus** [MatthewCallis/atom-date-helpers#3]
Steps to reproduce:

1. Launch any action (For example: Atom Date Helper: Toggle)

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.13
**Thrown From**: [atom-date-helpers](https://github.com/MatthewCallis/atom-date-helpers) package 3.0.0

### Stack Trace

Failed to activate the atom-date-helpers package

```
At _atom.TextEditor is not a constructor

TypeError: _atom.TextEditor is not a constructor
    at /packages/atom-date-helpers/lib/format-view.js:118:23)
    at Object.activate (/packages/atom-date-helpers/lib/atom-date-helpers.js:13:23)
    at Package.module.exports.Package.activateNow (/Users/alefort/Downloads/Atom.app/Contents/Resources/app/src/package.js:251:19)
    at /Users/alefort/Downloads/Atom.app/Contents/Resources/app/src/package.js:966:25
    at Function.module.exports.Emitter.simpleDispatch (/Users/alefort/Downloads/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/alefort/Downloads/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/alefort/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:246:20)
    at /Users/alefort/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/alefort/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:606:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/alefort/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:397:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/alefort/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:36)
    at HTMLDocument.<anonymous> (/Users/alefort/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:07.5.0 atom-date-helpers:toggle (input.hidden-input)
     -1:07.9.0 core:copy (input.hidden-input)
  2x -0:27.4.0 atom-date-helpers:toggle (input.hidden-input)
     -0:25.1.0 settings-view:open (input.hidden-input)
     -0:15.5.0 core:close (button.btn.icon.enablement.icon-playback-pause)
     -0:06.7.0 atom-date-helpers:toggle (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-date-helpers 3.0.0 
epoch-times 0.1.0 
iso8601-timestamp 0.1.1 
pretty-json 1.6.3 
```

**Comment by MatthewCallis** [comment]
I'll try to dig in to it when I get time!
